import type { KlashEngineVertical } from "./types";

/**
 * Klash Engine — registre de tous les verticaux (roadmap + actifs).
 * Source de vérité pour le scaffolding et la doc `docs/KLASH_ENGINE.md`.
 */
export const KLASH_ENGINE_CATALOG: KlashEngineVertical[] = [
  // ── Divertissement & Pop-Culture ──────────────────────────────────────────
  {
    slug: "screenklash",
    name: "ScreenKlash",
    emoji: "🎬",
    category: "entertainment",
    status: "active",
    appPackage: "screenklash",
    entities: [
      "Films",
      "Séries",
      "Sagas",
      "Personnages",
    ],
    apis: [
      { name: "TMDB", access: "free-key", envKey: "TMDB_API_KEY" },
      { name: "TVMaze", access: "open" },
    ],
    source: "screenklash",
    nouns: {
      item: "titre",
      items: "titres",
      collection: "saga",
      entity: "réalisateur",
    },
  },
  {
    slug: "animeklash",
    name: "AnimeKlash",
    emoji: "🎌",
    category: "entertainment",
    status: "active",
    appPackage: "animeklash",
    entities: [
      "Animés",
      "Openings",
      "Arcs",
      "Personnages",
    ],
    apis: [
      { name: "AniList (GraphQL)", access: "open" },
      { name: "Jikan", access: "open" },
    ],
    source: "anilist",
    nouns: {
      item: "entrée",
      items: "entrées",
      collection: "arc",
      entity: "animé",
    },
  },
  {
    slug: "bookklash",
    name: "BookKlash",
    emoji: "📚",
    category: "entertainment",
    status: "active",
    appPackage: "bookklash",
    entities: ["Livres", "Auteurs", "Genres"],
    apis: [
      { name: "Open Library", access: "open" },
      { name: "Google Books", access: "open" },
    ],
    source: "openlibrary",
    nouns: { item: "livre", items: "livres", entity: "auteur" },
  },
  {
    slug: "mangaklash",
    name: "MangaKlash",
    emoji: "📰",
    category: "entertainment",
    status: "active",
    appPackage: "mangaklash",
    entities: ["Mangas", "Chapitres", "Auteurs"],
    apis: [
      { name: "MangaDex", access: "open" },
      { name: "Jikan", access: "open" },
      { name: "AniList", access: "open" },
    ],
    source: "mangadex",
    nouns: { item: "chapitre", items: "chapitres", collection: "manga", entity: "auteur" },
  },
  {
    slug: "comicklash",
    name: "ComicKlash",
    emoji: "🦸",
    category: "entertainment",
    status: "active",
    appPackage: "comicklash",
    entities: ["Comics", "Personnages", "Arcs"],
    apis: [
      { name: "Comic Vine", access: "free-key", envKey: "COMIC_VINE_API_KEY" },
      { name: "Marvel API", access: "free-key", envKey: "MARVEL_API_KEY" },
    ],
    source: "comicvine",
    nouns: { item: "numéro", items: "numéros", collection: "arc", entity: "personnage" },
  },

  // ── Gaming & Geek ─────────────────────────────────────────────────────────
  {
    slug: "gameklash",
    name: "GameKlash",
    emoji: "🎮",
    category: "gaming",
    status: "active",
    appPackage: "gameklash",
    entities: ["Jeux", "Studios", "Genres", "Jeux rétro", "Jeux indés", "Consoles"],
    apis: [
      { name: "RAWG", access: "free-key", envKey: "RAWG_API_KEY" },
      { name: "Internet Archive API", access: "open" },
    ],
    source: "gameklash",
    nouns: { item: "jeu", items: "jeux", entity: "studio" },
    notes: "Fusion RetroKlash + IndieKlash dans GameKlash.",
  },
  {
    slug: "esportklash",
    name: "EsportKlash",
    emoji: "🏆",
    category: "gaming",
    status: "active",
    appPackage: "esportklash",
    entities: ["Teams", "Joueurs", "Tournois"],
    apis: [
      { name: "PandaScore", access: "free-key", envKey: "PANDASCORE_API_KEY" },
      { name: "Liquipedia API", access: "open" },
    ],
    source: "pandascore",
    nouns: { item: "match", items: "matchs", entity: "équipe" },
  },
  {
    slug: "boardklash",
    name: "BoardKlash",
    emoji: "🎲",
    category: "gaming",
    status: "active",
    appPackage: "boardklash",
    entities: ["Jeux de société", "Mécaniques"],
    apis: [{ name: "BoardGameGeek XML API", access: "open" }],
    source: "bgg",
    nouns: { item: "jeu", items: "jeux", entity: "mécanique" },
  },
  {
    slug: "cardklash",
    name: "CardKlash",
    emoji: "🃏",
    category: "gaming",
    status: "active",
    appPackage: "cardklash",
    entities: ["Cartes", "Decks", "Sets"],
    apis: [
      { name: "YGOPRODeck", access: "open" },
      { name: "Scryfall (Magic)", access: "open" },
    ],
    source: "scryfall",
    nouns: { item: "carte", items: "cartes", collection: "set", entity: "deck" },
  },
  {
    slug: "pokeklash",
    name: "PokeKlash",
    emoji: "⚡",
    category: "gaming",
    status: "active",
    appPackage: "pokeklash",
    entities: ["Pokémon", "Types", "Générations", "Évolutions"],
    apis: [{ name: "PokéAPI", access: "open" }],
    source: "pokeapi",
    nouns: {
      item: "Pokémon",
      items: "Pokémon",
      collection: "génération",
      entity: "type",
    },
  },
  {
    slug: "legoklash",
    name: "LegoKlash",
    emoji: "🧱",
    category: "gaming",
    status: "active",
    appPackage: "legoklash",
    entities: ["Sets", "Licences", "Minifigs"],
    apis: [
      { name: "Rebrickable API", access: "free-key", envKey: "REBRICKABLE_API_KEY" },
    ],
    source: "rebrickable",
    nouns: { item: "set", items: "sets", collection: "licence", entity: "licence" },
  },

  // ── Lifestyle ─────────────────────────────────────────────────────────────
  {
    slug: "tasteklash",
    name: "TasteKlash",
    emoji: "🍽️",
    category: "lifestyle",
    status: "active",
    appPackage: "tasteklash",
    entities: [
      "Plats",
      "Cocktails",
      "Cuisines",
      "Aliments",
      "Boissons",
    ],
    apis: [
      { name: "TheMealDB", access: "open" },
      { name: "TheCocktailDB", access: "open" },
      { name: "Open Food Facts", access: "open" },
    ],
    source: "themealdb",
    nouns: { item: "gourmandise", items: "gourmandises", entity: "cuisine" },
    notes: "Fusion DrinkKlash + FoodKlash.",
  },
  {
    slug: "petklash",
    name: "PetKlash",
    emoji: "🐶",
    category: "lifestyle",
    status: "active",
    appPackage: "petklash",
    entities: ["Races", "Espèces", "Comportements"],
    apis: [
      { name: "Dog CEO API", access: "open" },
      { name: "TheCatAPI", access: "open" },
      { name: "PetFinder", access: "free-key", envKey: "PETFINDER_API_KEY" },
    ],
    source: "dogceo",
    nouns: { item: "race", items: "races", entity: "espèce" },
  },

  // ── Sport ─────────────────────────────────────────────────────────────────
  {
    slug: "sportklash",
    name: "SportKlash",
    emoji: "⚽",
    category: "sport",
    status: "active",
    appPackage: "sportklash",
    entities: [
      "Multi-sport",
      "Football",
      "Basket (NBA)",
      "Formule 1",
      "MMA",
      "Tennis",
      "Équipes",
      "Joueurs",
      "Pilotes",
      "Fighters",
    ],
    apis: [
      { name: "TheSportsDB", access: "open" },
      { name: "BallDontLie API", access: "open" },
      { name: "Ergast API (Jolpica)", access: "open" },
      { name: "API-Sports MMA", access: "free-key", envKey: "API_SPORTS_KEY" },
    ],
    source: "thesportsdb",
    nouns: { item: "match", items: "matchs", entity: "équipe" },
    notes:
      "Fusion FootKlash + BasketKlash + F1Klash + FightKlash + TennisKlash dans SportKlash. FitnessKlash supprimé.",
  },

  // ── Tech ──────────────────────────────────────────────────────────────────

  // ── Art, Créativité & Musique ─────────────────────────────────────────────
  {
    slug: "musiklash",
    name: "MusiKlash",
    emoji: "🎵",
    category: "art-music",
    status: "active",
    appPackage: "musiklash",
    entities: ["Artistes", "Albums", "Morceaux"],
    apis: [{ name: "Deezer API", access: "open" }],
    source: "deezer",
    nouns: {
      item: "morceau",
      items: "morceaux",
      collection: "album",
      entity: "artiste",
    },
  },
  {
    slug: "rapklash",
    name: "RapKlash",
    emoji: "🎙️",
    category: "art-music",
    status: "active",
    appPackage: "rapklash",
    entities: ["Punchlines", "Clashs", "Albums"],
    apis: [{ name: "Deezer API", access: "open" }],
    source: "deezer",
    nouns: { item: "morceau", items: "morceaux", entity: "artiste" },
  },

  // ── Cross-universe ────────────────────────────────────────────────────────
  {
    slug: "worldklash",
    name: "WorldKlash",
    emoji: "🌍",
    category: "cross-universe",
    status: "active",
    appPackage: "worldklash",
    entities: [
      "Pays",
      "Capitales",
      "Cultures",
      "Drapeaux",
      "Régions",
      "Villes",
      "Lieux",
    ],
    apis: [
      { name: "RestCountries", access: "open" },
      { name: "Wikidata", access: "open" },
      { name: "OpenTripMap", access: "free-key", envKey: "OPENTRIPMAP_API_KEY" },
    ],
    source: "restcountries",
    nouns: { item: "lieu", items: "lieux", entity: "pays" },
    notes: "Fusion CountryKlash + TravelKlash.",
  },

  {
    slug: "islamklash",
    name: "IslamKlash",
    emoji: "🕌",
    category: "cross-universe",
    status: "active",
    appPackage: "islamklash",
    entities: ["Sourates", "Juz'", "Prophètes", "Savants", "Mosquées"],
    apis: [
      { name: "Données statiques (Coran)", access: "open" },
      { name: "Wikidata", access: "open" },
    ],
    source: "islamklash",
    nouns: { item: "sourate", items: "sourates", collection: "juz", entity: "prophète" },
    notes: "114 sourates + 25 prophètes en données statiques, savants/mosquées via Wikidata.",
  },

  // ── Interne ───────────────────────────────────────────────────────────────
  {
    slug: "demoklash",
    name: "DemoKlash",
    emoji: "🧪",
    category: "art-music",
    status: "active",
    appPackage: "demoklash",
    entities: ["Démo monorepo"],
    apis: [{ name: "Deezer API (démo)", access: "open" }],
    source: "deezer",
    nouns: { item: "item", items: "items" },
    notes: "Vertical technique — valide @klash/klash-app sans API dédiée.",
  },
];

export const KLASH_ENGINE_BY_SLUG: Record<string, KlashEngineVertical> =
  Object.fromEntries(KLASH_ENGINE_CATALOG.map((v) => [v.slug, v]));
