import type { KlashEngineVertical } from "./types";

/**
 * Klash Engine — registre de tous les verticaux (roadmap + actifs).
 * Source de vérité pour le scaffolding et la doc `docs/KLASH_ENGINE.md`.
 */
export const KLASH_ENGINE_CATALOG: KlashEngineVertical[] = [
  // ── Divertissement & Pop-Culture ──────────────────────────────────────────
  {
    slug: "movieklash",
    name: "MovieKlash",
    emoji: "🎬",
    category: "entertainment",
    status: "active",
    appPackage: "movieklash",
    entities: [
      "Films",
      "Réalisateurs",
      "Acteurs",
      "Personnages",
      "Transformations",
      "Pouvoirs",
    ],
    apis: [{ name: "TMDB", access: "free-key", envKey: "TMDB_API_KEY" }],
    source: "tmdb",
    nouns: {
      item: "film",
      items: "films",
      collection: "saga",
      entity: "réalisateur",
    },
  },
  {
    slug: "animeklash",
    name: "AnimeKlash",
    emoji: "🎌",
    category: "entertainment",
    status: "active",
    appPackage: "animeklash",
    entities: [
      "Animés",
      "Openings",
      "Arcs",
      "Personnages",
      "Transformations",
      "Pouvoirs",
    ],
    apis: [
      { name: "AniList (GraphQL)", access: "open" },
      { name: "Jikan", access: "open" },
    ],
    source: "anilist",
    nouns: {
      item: "entrée",
      items: "entrées",
      collection: "arc",
      entity: "animé",
    },
  },
  {
    slug: "seriesklash",
    name: "SeriesKlash",
    emoji: "📺",
    category: "entertainment",
    status: "active",
    appPackage: "seriesklash",
    entities: [
      "Séries",
      "Épisodes",
      "Saisons",
      "Personnages",
      "Transformations",
      "Pouvoirs",
    ],
    apis: [
      { name: "TVMaze", access: "open" },
      { name: "TMDB", access: "free-key", envKey: "TMDB_API_KEY" },
    ],
    source: "tvmaze",
    nouns: {
      item: "épisode",
      items: "épisodes",
      collection: "saison",
      entity: "série",
    },
  },
  {
    slug: "bookklash",
    name: "BookKlash",
    emoji: "📚",
    category: "entertainment",
    status: "active",
    appPackage: "bookklash",
    entities: ["Livres", "Auteurs", "Genres"],
    apis: [
      { name: "Open Library", access: "open" },
      { name: "Google Books", access: "open" },
    ],
    source: "openlibrary",
    nouns: { item: "livre", items: "livres", entity: "auteur" },
  },
  {
    slug: "mangaklash",
    name: "MangaKlash",
    emoji: "📰",
    category: "entertainment",
    status: "active",
    appPackage: "mangaklash",
    entities: ["Mangas", "Chapitres", "Auteurs"],
    apis: [
      { name: "MangaDex", access: "open" },
      { name: "Jikan", access: "open" },
      { name: "AniList", access: "open" },
    ],
    source: "mangadex",
    nouns: { item: "chapitre", items: "chapitres", collection: "manga", entity: "auteur" },
  },
  {
    slug: "comicklash",
    name: "ComicKlash",
    emoji: "🦸",
    category: "entertainment",
    status: "active",
    appPackage: "comicklash",
    entities: ["Comics", "Personnages", "Arcs"],
    apis: [
      { name: "Comic Vine", access: "free-key", envKey: "COMIC_VINE_API_KEY" },
      { name: "Marvel API", access: "free-key", envKey: "MARVEL_API_KEY" },
    ],
    source: "comicvine",
    nouns: { item: "numéro", items: "numéros", collection: "arc", entity: "personnage" },
  },

  // ── Gaming & Geek ─────────────────────────────────────────────────────────
  {
    slug: "gameklash",
    name: "GameKlash",
    emoji: "🎮",
    category: "gaming",
    status: "active",
    appPackage: "gameklash",
    entities: ["Jeux", "Studios", "Genres", "Boss"],
    apis: [
      { name: "RAWG", access: "free-key", envKey: "RAWG_API_KEY" },
      { name: "IGDB", access: "free-key", envKey: "IGDB_CLIENT_ID" },
    ],
    source: "rawg",
    nouns: { item: "jeu", items: "jeux", entity: "studio" },
  },
  {
    slug: "retroklash",
    name: "RetroKlash",
    emoji: "🕹️",
    category: "gaming",
    status: "active",
    appPackage: "retroklash",
    entities: ["Jeux rétro", "Consoles", "Ères"],
    apis: [
      { name: "RAWG (filtres rétro)", access: "free-key", envKey: "RAWG_API_KEY" },
      { name: "Internet Archive API", access: "open" },
    ],
    source: "rawg",
    nouns: { item: "jeu", items: "jeux", collection: "console", entity: "ère" },
  },
  {
    slug: "esportklash",
    name: "EsportKlash",
    emoji: "🏆",
    category: "gaming",
    status: "active",
    appPackage: "esportklash",
    entities: ["Teams", "Joueurs", "Tournois"],
    apis: [
      { name: "PandaScore", access: "free-key", envKey: "PANDASCORE_API_KEY" },
      { name: "Liquipedia API", access: "open" },
    ],
    source: "pandascore",
    nouns: { item: "match", items: "matchs", entity: "équipe" },
  },
  {
    slug: "boardklash",
    name: "BoardKlash",
    emoji: "🎲",
    category: "gaming",
    status: "active",
    appPackage: "boardklash",
    entities: ["Jeux de société", "Mécaniques"],
    apis: [{ name: "BoardGameGeek XML API", access: "open" }],
    source: "bgg",
    nouns: { item: "jeu", items: "jeux", entity: "mécanique" },
  },
  {
    slug: "cardklash",
    name: "CardKlash",
    emoji: "🃏",
    category: "gaming",
    status: "active",
    appPackage: "cardklash",
    entities: ["Cartes", "Decks", "Sets"],
    apis: [
      { name: "YGOPRODeck", access: "open" },
      { name: "Scryfall (Magic)", access: "open" },
    ],
    source: "scryfall",
    nouns: { item: "carte", items: "cartes", collection: "set", entity: "deck" },
  },
  {
    slug: "pokeklash",
    name: "PokeKlash",
    emoji: "⚡",
    category: "gaming",
    status: "active",
    appPackage: "pokeklash",
    entities: ["Pokémon", "Types", "Générations", "Évolutions"],
    apis: [{ name: "PokéAPI", access: "open" }],
    source: "pokeapi",
    nouns: {
      item: "Pokémon",
      items: "Pokémon",
      collection: "génération",
      entity: "type",
    },
  },
  {
    slug: "indieklash",
    name: "IndieKlash",
    emoji: "🧩",
    category: "gaming",
    status: "active",
    appPackage: "indieklash",
    entities: ["Jeux indés", "Jam", "Devs"],
    apis: [
      { name: "RAWG (filtres indie)", access: "free-key", envKey: "RAWG_API_KEY" },
      { name: "itch.io API", access: "open" },
    ],
    source: "rawg",
    nouns: { item: "jeu", items: "jeux", collection: "tag", entity: "dev" },
  },
  {
    slug: "legoklash",
    name: "LegoKlash",
    emoji: "🧱",
    category: "gaming",
    status: "active",
    appPackage: "legoklash",
    entities: ["Sets", "Licences", "Minifigs"],
    apis: [
      { name: "Rebrickable API", access: "free-key", envKey: "REBRICKABLE_API_KEY" },
    ],
    source: "rebrickable",
    nouns: { item: "set", items: "sets", collection: "licence", entity: "licence" },
  },

  // ── Lifestyle ─────────────────────────────────────────────────────────────
  {
    slug: "foodklash",
    name: "FoodKlash",
    emoji: "🍕",
    category: "lifestyle",
    status: "active",
    appPackage: "foodklash",
    entities: [
      "Plats",
      "Recettes",
      "Cuisines",
      "Aliments",
      "Fruits",
      "Légumes",
      "Fast-food",
    ],
    apis: [
      { name: "TheMealDB", access: "open" },
      { name: "Open Food Facts", access: "open" },
    ],
    source: "themealdb",
    nouns: { item: "plat", items: "plats", entity: "cuisine" },
  },
  {
    slug: "drinkklash",
    name: "DrinkKlash",
    emoji: "🍷",
    category: "lifestyle",
    status: "active",
    appPackage: "drinkklash",
    entities: ["Cocktails", "Vins", "Bières", "Boissons"],
    apis: [
      { name: "TheCocktailDB", access: "open" },
      { name: "Open Beer DB", access: "open" },
    ],
    source: "thecocktaildb",
    nouns: { item: "boisson", items: "boissons", entity: "cocktail" },
  },
  {
    slug: "travelklash",
    name: "TravelKlash",
    emoji: "✈️",
    category: "lifestyle",
    status: "active",
    appPackage: "travelklash",
    entities: ["Destinations", "Pays", "Villes"],
    apis: [
      { name: "RestCountries", access: "open" },
      { name: "OpenTripMap", access: "free-key", envKey: "OPENTRIPMAP_API_KEY" },
    ],
    source: "restcountries",
    nouns: { item: "lieu", items: "lieux", collection: "région", entity: "destination" },
  },
  {
    slug: "fashionklash",
    name: "FashionKlash",
    emoji: "👗",
    category: "lifestyle",
    status: "active",
    appPackage: "fashionklash",
    entities: ["Marques", "Créateurs", "Styles", "Vêtements"],
    apis: [
      { name: "Open Fashion (Livostyle Open Data)", access: "open" },
      { name: "Wikimedia API", access: "open" },
    ],
    source: "openfashion",
    nouns: { item: "pièce", items: "pièces", entity: "marque" },
    notes:
      "Catalogue MIT (~2,6k pièces femme) via GitHub ; Wikimedia pour visuels marques. Pas d'API REST temps réel.",
  },
  {
    slug: "sneakerklash",
    name: "SneakerKlash",
    emoji: "👟",
    category: "lifestyle",
    status: "active",
    appPackage: "sneakerklash",
    entities: ["Colorways", "Drops", "Modèles"],
    apis: [
      { name: "SneaksAPI", access: "scraping" },
      { name: "Kicks On Fire", access: "scraping" },
    ],
    source: "sneaks",
    nouns: { item: "colorway", items: "colorways", collection: "drop", entity: "modèle" },
    notes:
      "Scraping StockX/GOAT via sneaks-api — fragile, sans clé API. Proxy obligatoire (/api/content/*). Voir apps/sneakerklash/SNEAKS_API.md.",
  },
  {
    slug: "petklash",
    name: "PetKlash",
    emoji: "🐶",
    category: "lifestyle",
    status: "active",
    appPackage: "petklash",
    entities: ["Races", "Espèces", "Comportements"],
    apis: [
      { name: "Dog CEO API", access: "open" },
      { name: "TheCatAPI", access: "open" },
      { name: "PetFinder", access: "free-key", envKey: "PETFINDER_API_KEY" },
    ],
    source: "dogceo",
    nouns: { item: "race", items: "races", entity: "espèce" },
  },

  // ── Sport ─────────────────────────────────────────────────────────────────
  {
    slug: "sportklash",
    name: "SportKlash",
    emoji: "⚽",
    category: "sport",
    status: "active",
    appPackage: "sportklash",
    entities: ["Sports", "Équipes", "Joueurs"],
    apis: [{ name: "TheSportsDB", access: "open" }],
    source: "thesportsdb",
    nouns: { item: "match", items: "matchs", entity: "équipe" },
  },
  {
    slug: "footklash",
    name: "FootKlash",
    emoji: "⚽",
    category: "sport",
    status: "active",
    appPackage: "footklash",
    entities: ["Clubs", "Joueurs", "Ligues"],
    apis: [
      { name: "TheSportsDB", access: "open" },
      { name: "Football-Data.org", access: "free-key", envKey: "FOOTBALL_DATA_API_KEY" },
    ],
    source: "thesportsdb",
    nouns: { item: "match", items: "matchs", entity: "club" },
  },
  {
    slug: "basketklash",
    name: "BasketKlash",
    emoji: "🏀",
    category: "sport",
    status: "planned",
    entities: ["Équipes", "Joueurs", "Saisons"],
    apis: [
      { name: "TheSportsDB", access: "open" },
      { name: "BallDontLie API", access: "open" },
    ],
    source: "balldontlie",
    nouns: { item: "match", items: "matchs", entity: "équipe" },
  },
  {
    slug: "tennisklash",
    name: "TennisKlash",
    emoji: "🎾",
    category: "sport",
    status: "active",
    appPackage: "tennisklash",
    entities: ["Joueurs", "Tournois", "Surfaces"],
    apis: [
      { name: "TheSportsDB", access: "open" },
      { name: "RapidAPI Tennis", access: "free-key", envKey: "RAPIDAPI_KEY" },
    ],
    source: "thesportsdb",
    nouns: { item: "match", items: "matchs", entity: "joueur" },
    notes:
      "MVP via TheSportsDB (clé gratuite 123 ou THESPORTSDB_API_KEY premium). RapidAPI Tennis optionnel (RAPIDAPI_KEY).",
  },
  {
    slug: "f1klash",
    name: "F1Klash",
    emoji: "🏎️",
    category: "sport",
    status: "planned",
    entities: ["Pilotes", "Écuries", "Circuits"],
    apis: [
      { name: "Ergast API", access: "open" },
      { name: "OpenF1 API", access: "open" },
    ],
    source: "ergast",
    nouns: { item: "course", items: "courses", entity: "pilote" },
  },
  {
    slug: "fightklash",
    name: "FightKlash",
    emoji: "🥊",
    category: "sport",
    status: "active",
    appPackage: "fightklash",
    entities: ["Fighters", "Styles", "Organisations"],
    apis: [
      { name: "API-Sports MMA", access: "free-key", envKey: "API_SPORTS_KEY" },
      { name: "Wikipedia API", access: "open" },
    ],
    source: "api-sports",
    nouns: { item: "combat", items: "combats", entity: "fighter" },
  },
  {
    slug: "fitnessklash",
    name: "FitnessKlash",
    emoji: "🏋️",
    category: "sport",
    status: "active",
    appPackage: "fitnessklash",
    entities: ["Exercices", "Programmes", "Muscles"],
    apis: [
      { name: "ExerciseDB", access: "open" },
      { name: "Wger API", access: "open" },
    ],
    source: "wger",
    nouns: { item: "exercice", items: "exercices", entity: "muscle" },
  },

  // ── Tech ──────────────────────────────────────────────────────────────────
  {
    slug: "carklash",
    name: "CarKlash",
    emoji: "🚗",
    category: "tech",
    status: "active",
    appPackage: "carklash",
    entities: ["Voitures", "Marques", "Modèles"],
    apis: [
      { name: "CarQuery", access: "open" },
      { name: "NHTSA", access: "open" },
    ],
    source: "carquery",
    nouns: { item: "modèle", items: "modèles", entity: "marque" },
  },

  // ── Art, Créativité & Musique ─────────────────────────────────────────────
  {
    slug: "musiklash",
    name: "MusiKlash",
    emoji: "🎵",
    category: "art-music",
    status: "active",
    appPackage: "musiklash",
    entities: ["Artistes", "Albums", "Morceaux"],
    apis: [
      { name: "Deezer API", access: "open" },
      { name: "MusicBrainz", access: "open" },
    ],
    source: "deezer",
    nouns: {
      item: "morceau",
      items: "morceaux",
      collection: "album",
      entity: "artiste",
    },
  },
  {
    slug: "rapklash",
    name: "RapKlash",
    emoji: "🎙️",
    category: "art-music",
    status: "active",
    appPackage: "rapklash",
    entities: ["Punchlines", "Clashs", "Albums"],
    apis: [
      { name: "Deezer API", access: "open" },
      { name: "Genius API", access: "free-key", envKey: "GENIUS_ACCESS_TOKEN" },
    ],
    source: "deezer",
    nouns: { item: "morceau", items: "morceaux", entity: "artiste" },
    notes:
      "Verticale rap spécialisée — peut partager l'app MusiKlash avec config/i18n dédiés.",
  },

  // ── Cross-universe ────────────────────────────────────────────────────────
  {
    slug: "countryklash",
    name: "CountryKlash",
    emoji: "🌍",
    category: "cross-universe",
    status: "planned",
    entities: [
      "Pays",
      "Capitales",
      "Cultures",
      "Drapeaux",
      "Lieux",
      "Villes",
    ],
    apis: [
      { name: "RestCountries", access: "open" },
      { name: "Wikidata", access: "open" },
    ],
    source: "restcountries",
    nouns: { item: "lieu", items: "lieux", entity: "pays" },
  },
  {
    slug: "characterklash",
    name: "CharacterKlash",
    emoji: "🧙",
    category: "cross-universe",
    status: "active",
    appPackage: "characterklash",
    entities: ["Cross-universe battles"],
    apis: [
      { name: "AniList", access: "open" },
      { name: "TMDB", access: "free-key", envKey: "TMDB_API_KEY" },
    ],
    source: "characterklash",
    nouns: { item: "personnage", items: "personnages", entity: "héros" },
    notes:
      "MVP : AniList (persos anime) + TMDB (stars cinéma). Marvel API / RAWG prévus roadmap.",
  },
  {
    slug: "powerklash",
    name: "PowerKlash",
    emoji: "🐉",
    category: "cross-universe",
    status: "active",
    appPackage: "powerklash",
    entities: ["Power scaling", "Tier lists"],
    apis: [
      { name: "AniList", access: "open" },
      { name: "Jikan", access: "open" },
      { name: "Marvel API", access: "free-key", envKey: "MARVEL_API_KEY" },
    ],
    source: "anilist",
    nouns: {
      item: "personnage",
      items: "personnages",
      collection: "univers",
      entity: "série",
    },
    notes: "Tier lists de puissance — MVP AniList personnages ; Jikan/Marvel en complément ultérieur.",
  },

  // ── Interne ───────────────────────────────────────────────────────────────
  {
    slug: "demoklash",
    name: "DemoKlash",
    emoji: "🧪",
    category: "art-music",
    status: "active",
    appPackage: "demoklash",
    entities: ["Démo monorepo"],
    apis: [{ name: "Deezer API (démo)", access: "open" }],
    source: "deezer",
    nouns: { item: "item", items: "items" },
    notes: "Vertical technique — valide @klash/klash-app sans API dédiée.",
  },
];

export const KLASH_ENGINE_BY_SLUG: Record<string, KlashEngineVertical> =
  Object.fromEntries(KLASH_ENGINE_CATALOG.map((v) => [v.slug, v]));
